FROM google/cloud-sdk:274.0.1-alpine

RUN gcloud -q components install beta cloud-firestore-emulator \
    && apk --no-cache add openjdk11-jre-headless

EXPOSE 8080

CMD ["gcloud", "beta", "emulators", "firestore", "start", "--host-port=0.0.0.0:8080"]
